[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 8080


